language: python

python:
  - "2.6"
  - "2.7"
  # Removed this since it's broken.
  # - "3.1"
  - "3.2"
  - "3.3"
  - "pypy"

install:
  - pip install -r requirements.txt --use-mirrors
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"

script:
  - py.test

branches:
    only:
        - master
